### ISSUE TITLE
Accept a client string endpoint description which pairs with the server string endpoint description

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#269] opened 2020-08-21 20:12 UTC
From https://github.com/LeastAuthority/magic-folder/issues/222:

> So: magic-folder init --listen-endpoint tcp:4321:interface=localhost would "just work" and implicitly use --api-client-endpoint tcp:localhost:4321. But if you did magic-folder init --listen-endpoint onion:80 then it would be an error (because we don't know how to make a client-style endpoint for that kind of server endpoint) and you'd have to pass --api-client-endpoint tor:<the actual address>.onion:80 as well.

**Comment by meejah** [comment] 2020-08-28 08:19
Implemented in https://github.com/LeastAuthority/magic-folder/pull/252 (and kind-of a dupe of https://github.com/LeastAuthority/magic-folder/issues/251 ?)

**Closed by meejah** 2020-08-28 08:19 UTC
