### ISSUE TITLE
All error repsonse should have a JSON body.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#376] opened 2021-06-01 16:11 UTC
There was code to do this originally in https://github.com/tp-la/magic-folder/pull/1
```diff
diff --git src/magic_folder/web.py src/magic_folder/web.py
--- src/magic_folder/web.py
+++ src/magic_folder/web.py
@@ -138,6 +138,9 @@ class BearerTokenAuthorization(Resource,
         return Unauthorized()
 
 
+from werkzeug.exceptions import HTTPException
+
+
 @attr.s
 class APIv1(object):
     """
@@ -153,6 +156,12 @@ class APIv1(object):
 
     app = Klein()
 
+    @app.handle_errors(HTTPException)
+    def internal_error(self, request, failure):
+        request.setResponseCode(failure.value.code or INTERNAL_SERVER_ERROR)
+        _application_json(request)
+        return json.dumps({"reason": failure.value.description}).encode("utf8")
+
     @app.route("/status")
     @inlineCallbacks
     def status(self, request):
```
But that isn't entirely correct, as `HTTPException` also encodes headers that we will need to add, if we override klein's handling of the exception. (Additionally we may want to special case `werkzeug.routing.RequestRedirect` which is a redirect not an error)

**Comment by tomprince** [comment] 2021-06-01 16:19
The relevant code in `klein` is [here](https://github.com/twisted/klein/blob/20.6.0/src/klein/_resource.py#L241-L250). We can probably ignore the body but we should maintain the headers. (Note we can't use `HTTPException.get_headers`, as `werkzeug.routing.RequestRedirect` bypasses that).

**Comment by tomprince** [comment] 2021-06-01 16:20
We should probably also turn other exceptions into 500s and log the error.

**Comment by meejah** [comment] 2021-06-08 20:22
related / partial duplicate of https://github.com/LeastAuthority/magic-folder/issues/330

**Closed** 2021-06-16 18:01 UTC
